import { greyGreen } from "../../colors";

export const container = {
  backgroundColor: greyGreen,
  borderRadius: 8,
  pt: { xs: 2.5, md: 15 },
  pb: 2.5,
  pr: 2.5,
  pl: 2.5,
  transition: "all 0.75s",
  transitionDelay: "0.35s",
  "& .nameContainer": {
    display: { md: "flex" },
    justifyContent: "end",
    transition: "0.75s",
    transitionDelay: "0.35s",
    "& .myName": {
      display: { xs: "inline-block", md: "none" },
      color: "white",
      fontSize: { xs: "2.5rem", sm: "5rem" },
      lineHeight: 1,
      mt: { xs: 0.5, sm: 1 },
      mb: { xs: 0.5, sm: 1 },
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .myNamex": {
      display: { xs: "inline-block", md: "none" },
      color: "white",
      fontSize: { xs: "5rem", sm: "8rem" },
      lineHeight: 1,
      mt: { xs: 0.5, sm: 1 },
      mb: { xs: 0.5, sm: 1 },
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .avatar2": {
      display: { xs: "none", md: "inline-block" },
      height: "100%",
      width: 130,
      backgroundColor: "black",
      p: 0.5,
      transform: "scaleX(-1)",
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .avatar2x": {
      display: { xs: "none", md: "inline-block" },
      height: "25%",
      width: 75,
      backgroundColor: "black",
      p: 0.5,
      transform: "scaleX(-1)",
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
  },
  "& .avatarContainer": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "left",
    mt: { xs: 0.5, sm: 1 },
    mb: { xs: 0.5, sm: 1 },
    transition: "0.75s",
    transitionDelay: "0.35s",
    "& .avatar": {
      display: { xs: "inline-block", md: "none" },
      height: "100%",
      width: 130,
      backgroundColor: "black",
      p: 0.5,
      transform: "scaleX(-1)",
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .avatarx": {
      display: { xs: "inline-block", md: "none" },
      height: "75%",
      width: 75,
      backgroundColor: "black",
      p: 0.5,
      transform: "scaleX(-1)",
      transition: "0.75s",
      transitionDelay: "0.35s",
    },

    "& .myName2": {
      display: { xs: "none", md: "inline-block" },
      color: "white",
      fontSize: { xs: "2.5rem", sm: "5rem" },
      lineHeight: 1,
      mt: { xs: 0.5, sm: 1 },
      mb: { xs: 0.5, sm: 1 },
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .myName2x": {
      display: { xs: "none", md: "inline-block" },
      color: "white",
      fontSize: { xs: "5rem", sm: "8rem" },
      lineHeight: 1,
      mt: { xs: 0.5, sm: 1 },
      mb: { xs: 0.5, sm: 1 },
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .roleContainer2": {
      display: { xs: "none", md: "flex" },
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderRadius: 50,
      border: "1px solid white",
      width: "100%",
      pl: 1,
      pr: 1,
      mt: { xs: 0.5, sm: 1 },
      mb: { xs: 0.5, sm: 1 },
      transition: "0.75s",
      transitionDelay: "0.35s",
      "& .roleText": {
        color: "white",
        transition: "0.75s",
        transitionDelay: "0.35s",
      },
      "& .roleButton": {
        backgroundColor: "#6d7676",
        "& .roleIcon": {
          color: "white",
          transition: "0.75s",
          transitionDelay: "0.35s",
        },
      },
    },
  },

  "& .roleContainer": {
    display: { xs: "flex", md: "none" },
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 50,
    border: "1px solid white",
    width: "100%",
    pl: 1,
    pr: 1,
    mt: { xs: 0.5, sm: 1 },
    mb: { xs: 0.5, sm: 1 },
    transition: "0.75s",
    transitionDelay: "0.35s",
    "& .roleText": {
      color: "white",
      transition: "0.75s",
      transitionDelay: "0.35s",
    },
    "& .roleButton": {
      backgroundColor: "#6d7676",
      transition: "0.75s",
      transitionDelay: "0.35s",
      "& .roleIcon": {
        color: "white",
        transition: "0.75s",
        transitionDelay: "0.35s",
      },
    },
  },
  img: {
    transition: "1s",
    "&:hover": {
      cursor: "progress",
      transform: "rotate(360deg)",
      transition: "5s",
    },
  },
};
